actions:
  - id: gitleaks
    name: Git Leaks
    step:
      name: scan-and-report-leaks
    category: "security"
    description: "scan your codebase (20 last commits) and reports leaks"
    icon: "https://w6d-public.s3.eu-west-3.amazonaws.com/pictures/gitleaks.png"
    fields: []
    targets:
      componentId: project.componentId
      ref: actions.id
    image: w6dio/docker-gitleaks:v0.0.6
    script: |
      #!/bin/sh
      set -e
      mkdir -p $(workspaces.artifacts.path)/git-leaks
      gitleaks --path=$(workspaces.source.path) --config-path=/run/configs/leaky-repo.toml -v --report=$(workspaces.artifacts.path)/git-leaks/report-pathsecretsscan.json --depth=5
      echo -e "\e[32msuccess"