listen:
  metrics: ":8080"
  probe: ":8081"
leaderElection:
  leaderElect: true
  resourceName: ciops.ci.w6d.io
pipelinerun:
  prefix: "pipelinerun"
  workspaces:
    - emptyDir: {}
      name: ws
  workspacePipelineTaskBinding:
    - name: artifacts
      subPath: artifacts
      workspace: ws
    - name: source
      subPath: source
      workspace: ws
  podTemplate:
    nodeSelector:
      role: spot
    tolerations:
      - effect: NoSchedule
        key: spotInstance
        operator: Equal
        value: "true"
namespace: ""
