apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

labels:
- includeSelectors: true
  pairs:
    component: server

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - config.yaml
  name: config
- files:
  - default_actions.yaml
  - actions.yaml
  name: config-extra

images:
- name: ciops
  newName: w6dio/ciops
  newTag: feat-pipelinesource
- name: controller
  newName: w6dio/ciops
  newTag: webhook
