resources:
- webhook.yaml
- manifests.yaml
- service.yaml

labels:
- includeSelectors: true
  pairs:
    component: webhook
generatorOptions:
  disableNameSuffixHash: true

configurations:
- kustomizeconfig.yaml

configMapGenerator:
- files:
  - webhook_config.yaml
  name: webhook-config

patchesStrategicMerge:
- webhookcainjection_patch.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ciops
  newName: w6dio/ciops
  newTag: feat-pipelinesource
- name: webhook
  newName: w6dio/ciops
  newTag: webhook
