apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: ciops
  name: ciops-metrics-service
  namespace: w6d-ops
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: ciops
