# permissions for end users to view eventbudgets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventbudget-viewer-role
rules:
- apiGroups:
  - ci.w6d.io
  resources:
  - eventbudgets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ci.w6d.io
  resources:
  - eventbudgets/status
  verbs:
  - get
