# permissions for end users to view events.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: event-viewer-role
rules:
- apiGroups:
  - ci.w6d.io
  resources:
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ci.w6d.io
  resources:
  - events/status
  verbs:
  - get
