# permissions for end users to view factbudgets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: factbudget-viewer-role
rules:
- apiGroups:
  - ci.w6d.io
  resources:
  - factbudgets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ci.w6d.io
  resources:
  - factbudgets/status
  verbs:
  - get
