# permissions for end users to edit factbudgets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: factbudget-editor-role
rules:
- apiGroups:
  - ci.w6d.io
  resources:
  - factbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ci.w6d.io
  resources:
  - factbudgets/status
  verbs:
  - get
