# permissions for end users to view facts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fact-viewer-role
rules:
- apiGroups:
  - ci.w6d.io
  resources:
  - facts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ci.w6d.io
  resources:
  - facts/status
  verbs:
  - get
