# permissions for end users to edit facts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fact-editor-role
rules:
- apiGroups:
  - ci.w6d.io
  resources:
  - facts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ci.w6d.io
  resources:
  - facts/status
  verbs:
  - get
