# permissions for end users to view pipelinesources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipelinesource-viewer-role
rules:
- apiGroups:
  - ci.w6d.io
  resources:
  - pipelinesources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ci.w6d.io
  resources:
  - pipelinesources/status
  verbs:
  - get
